package exception;

import org.junit.runner.JUnitCore;
import org.junit.runner.Result;

public class TestException {
	public static void main(String[] args) {
		Result result = JUnitCore(CalculatorTestEx.class);
	}

}
